// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users-service.proto

package io.example.grpc.users;

public interface TokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>.ResponseStatus response_status = 2;</code>
   */
  boolean hasResponseStatus();
  /**
   * <code>.ResponseStatus response_status = 2;</code>
   */
  ResponseStatus getResponseStatus();
  /**
   * <code>.ResponseStatus response_status = 2;</code>
   */
  ResponseStatusOrBuilder getResponseStatusOrBuilder();
}
