// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users-service.proto

package io.example.grpc.users;

public interface ResponseStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string details = 2;</code>
   */
  String getDetails();
  /**
   * <code>string details = 2;</code>
   */
  com.google.protobuf.ByteString
      getDetailsBytes();
}
