// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users-service.proto

package io.example.grpc.users;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.User user = 1;</code>
   */
  User getUser();
  /**
   * <code>.User user = 1;</code>
   */
  UserOrBuilder getUserOrBuilder();

  /**
   * <code>.ResponseStatus response_status = 2;</code>
   */
  boolean hasResponseStatus();
  /**
   * <code>.ResponseStatus response_status = 2;</code>
   */
  ResponseStatus getResponseStatus();
  /**
   * <code>.ResponseStatus response_status = 2;</code>
   */
  ResponseStatusOrBuilder getResponseStatusOrBuilder();
}
