// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users-service.proto

package io.example.grpc.users;

public interface UsernameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Username)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
